# Generated by Django 5.0.2 on 2024-03-08 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('teacherid', models.AutoField(db_column='teacherId', primary_key=True, serialize=False)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('password', models.CharField(blank=True, max_length=255, null=True)),
                ('lastname', models.CharField(blank=True, db_column='Lastname', max_length=255, null=True)),
                ('firstname', models.CharField(blank=True, db_column='Firstname', max_length=250, null=True)),
                ('middlename', models.CharField(blank=True, db_column='Middlename', max_length=255, null=True)),
                ('suffix', models.CharField(db_column='Suffix', max_length=255)),
                ('age', models.IntegerField(blank=True, db_column='Age', null=True)),
                ('dateofbirth', models.CharField(blank=True, db_column='DateOfBirth', max_length=255, null=True)),
                ('placeofbirth', models.CharField(blank=True, db_column='PlaceOfBirth', max_length=255, null=True)),
                ('contactno', models.CharField(blank=True, db_column='ContactNo', max_length=255, null=True)),
                ('gender', models.CharField(blank=True, db_column='Gender', max_length=255, null=True)),
                ('maritalstatus', models.CharField(blank=True, db_column='MaritalStatus', max_length=255, null=True)),
                ('citizenship', models.CharField(blank=True, db_column='Citizenship', max_length=255, null=True)),
                ('religion', models.CharField(blank=True, db_column='Religion', max_length=255, null=True)),
                ('address', models.CharField(blank=True, db_column='Address', max_length=255, null=True)),
                ('homeaddress', models.CharField(db_column='HomeAddress', max_length=255)),
                ('gacademicyearid', models.IntegerField(db_column='GAcademicYearID')),
            ],
            options={
                'db_table': 'teachers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LmsAllbooks',
            fields=[
                ('book_id', models.AutoField(primary_key=True, serialize=False)),
                ('class_id', models.IntegerField()),
                ('catid', models.IntegerField(db_column='catID')),
                ('book_title', models.CharField(max_length=255)),
                ('callno', models.CharField(db_column='callNo', max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('datepublish', models.CharField(max_length=255)),
                ('availability', models.CharField(max_length=255)),
                ('dateadded', models.DateTimeField(db_column='dateAdded')),
            ],
            options={
                'db_table': 'lms_allbooks',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='LmsBookcategory',
            fields=[
                ('cat_id', models.AutoField(primary_key=True, serialize=False)),
                ('bookcategory', models.CharField(db_column='bookCategory', max_length=255)),
            ],
            options={
                'db_table': 'lms_bookcategory',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='LmsBorrow',
            fields=[
                ('brid', models.AutoField(db_column='BRID', primary_key=True, serialize=False)),
                ('lrn_no', models.CharField(max_length=255)),
                ('book_id', models.IntegerField()),
                ('status', models.CharField(max_length=255)),
                ('datetrack', models.DateTimeField(db_column='dateTrack')),
            ],
            options={
                'db_table': 'lms_borrow',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='LmsBorrowreturn',
            fields=[
                ('brid', models.AutoField(db_column='BRID', primary_key=True, serialize=False)),
                ('lrn_no', models.IntegerField()),
                ('book_id', models.IntegerField()),
                ('status', models.CharField(max_length=255)),
                ('returndateuntil', models.CharField(db_column='returnDateUntil', max_length=255)),
                ('dateborrow', models.CharField(db_column='dateBorrow', max_length=255)),
                ('datereturn', models.CharField(db_column='dateReturn', max_length=255)),
            ],
            options={
                'db_table': 'lms_borrowreturn',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='LmsCategory',
            fields=[
                ('catid', models.AutoField(db_column='catID', primary_key=True, serialize=False)),
                ('category', models.CharField(db_column='Category', max_length=255)),
            ],
            options={
                'db_table': 'lms_category',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='LmsClassification',
            fields=[
                ('class_id', models.AutoField(primary_key=True, serialize=False)),
                ('bookclassification', models.CharField(db_column='bookClassification', max_length=255)),
            ],
            options={
                'db_table': 'lms_classification',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='LmsFinefees',
            fields=[
                ('fine_id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=255)),
                ('penalty', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'lms_finefees',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='LmsLogs',
            fields=[
                ('logid', models.AutoField(db_column='LogID', primary_key=True, serialize=False)),
                ('lrn_no', models.IntegerField()),
                ('book_id', models.IntegerField()),
                ('status', models.CharField(max_length=255)),
                ('datetrack', models.DateTimeField(db_column='dateTrack')),
                ('dateuntil', models.CharField(db_column='dateUntil', max_length=255)),
            ],
            options={
                'db_table': 'lms_logs',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='LmsNonstudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=20, null=True)),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.CharField(blank=True, max_length=50, null=True)),
                ('contact', models.CharField(blank=True, max_length=20, null=True)),
                ('dateregistered', models.DateField(blank=True, null=True)),
                ('password', models.CharField(blank=True, max_length=10, null=True)),
                ('status', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'lms_nonstudent',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='LmsReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brid', models.IntegerField(db_column='BRID')),
                ('lrn_no', models.CharField(max_length=255)),
                ('book_id', models.IntegerField()),
                ('status', models.CharField(max_length=255)),
                ('datereturn', models.DateTimeField(db_column='dateReturn')),
            ],
            options={
                'db_table': 'lms_return',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='LmsStudentrecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lrn_no', models.CharField(max_length=255, unique=True)),
                ('studentname', models.CharField(db_column='studentName', max_length=255)),
                ('grade', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'lms_studentrecord',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('logid', models.AutoField(db_column='LogID', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Name', max_length=100)),
                ('role', models.CharField(db_column='Role', max_length=100)),
                ('marks', models.CharField(db_collation='utf8mb4_unicode_ci', db_column='Marks', max_length=255)),
                ('dateop', models.DateTimeField(db_column='DateOp')),
            ],
            options={
                'db_table': 'logs',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('registerid', models.AutoField(db_column='RegisterID', primary_key=True, serialize=False)),
                ('refno', models.CharField(blank=True, db_column='RefNo', max_length=255, null=True)),
                ('qrcode', models.TextField(blank=True, null=True)),
                ('lrn', models.CharField(blank=True, db_column='LRN', max_length=255, null=True)),
                ('lastname', models.CharField(blank=True, db_column='LastName', max_length=255, null=True)),
                ('firstname', models.CharField(blank=True, db_column='FirstName', max_length=255, null=True)),
                ('middlename', models.CharField(blank=True, db_column='MiddleName', max_length=255, null=True)),
                ('suffix', models.CharField(blank=True, db_column='Suffix', max_length=255, null=True)),
                ('gender', models.CharField(blank=True, db_column='Gender', max_length=255, null=True)),
                ('birthdate', models.CharField(blank=True, db_column='BirthDate', max_length=255, null=True)),
                ('birthplace', models.CharField(blank=True, db_column='BirthPlace', max_length=255, null=True)),
                ('address', models.CharField(blank=True, db_column='Address', max_length=255, null=True)),
                ('ethnicity', models.CharField(blank=True, db_column='Ethnicity', max_length=255, null=True)),
                ('religion', models.CharField(blank=True, db_column='Religion', max_length=255, null=True)),
                ('contact', models.CharField(blank=True, db_column='Contact', max_length=255, null=True)),
                ('email', models.CharField(blank=True, db_column='Email', max_length=255, null=True)),
                ('level', models.CharField(blank=True, db_column='Level', max_length=255, null=True)),
                ('strand', models.CharField(blank=True, db_column='Strand', max_length=255, null=True)),
                ('fathersname', models.CharField(blank=True, db_column='FathersName', max_length=255, null=True)),
                ('fathersoccupation', models.CharField(blank=True, db_column='FathersOccupation', max_length=255, null=True)),
                ('fatherscontact', models.CharField(blank=True, db_column='FathersContact', max_length=255, null=True)),
                ('mothersname', models.CharField(blank=True, db_column='MothersName', max_length=255, null=True)),
                ('mothersoccupation', models.CharField(blank=True, db_column='MothersOccupation', max_length=255, null=True)),
                ('motherscontact', models.CharField(blank=True, db_column='MothersContact', max_length=255, null=True)),
                ('guardiansname', models.CharField(blank=True, db_column='GuardiansName', max_length=255, null=True)),
                ('guardiansoccupation', models.CharField(blank=True, db_column='GuardiansOccupation', max_length=255, null=True)),
                ('guardianscontact', models.CharField(blank=True, db_column='GuardiansContact', max_length=255, null=True)),
                ('curriculum', models.CharField(blank=True, db_column='Curriculum', max_length=255, null=True)),
                ('civilstatus', models.CharField(blank=True, db_column='CivilStatus', max_length=255, null=True)),
                ('juniorhigh', models.CharField(blank=True, db_column='JuniorHigh', max_length=255, null=True)),
                ('seniorhigh', models.CharField(blank=True, db_column='SeniorHigh', max_length=255, null=True)),
                ('junioraddress', models.CharField(blank=True, db_column='JuniorAddress', max_length=255, null=True)),
                ('senioraddress', models.CharField(blank=True, db_column='SeniorAddress', max_length=255, null=True)),
                ('techvoccourse', models.CharField(blank=True, db_column='TechvocCourse', max_length=255, null=True)),
                ('culturalminoritygroup', models.CharField(blank=True, db_column='CulturalMinorityGroup', max_length=255, null=True)),
                ('disabilities', models.CharField(blank=True, db_column='Disabilities', max_length=255, null=True)),
                ('birthcert', models.CharField(blank=True, db_column='BirthCert', max_length=255, null=True)),
                ('form137', models.CharField(blank=True, db_column='Form137', max_length=255, null=True)),
                ('goodmoral', models.CharField(blank=True, db_column='GoodMoral', max_length=255, null=True)),
                ('reportcard', models.CharField(blank=True, db_column='ReportCard', max_length=255, null=True)),
                ('esc', models.CharField(blank=True, db_column='ESC', max_length=255, null=True)),
                ('psa', models.CharField(blank=True, db_column='PSA', max_length=255, null=True)),
                ('number_2x2', models.CharField(blank=True, db_column='2x2', max_length=255, null=True)),
                ('dateregistered', models.CharField(blank=True, db_column='DateRegistered', max_length=255, null=True)),
                ('password', models.CharField(blank=True, max_length=45, null=True)),
                ('status', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'student',
                'managed': True,
            },
        ),
    ]
